using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Windows.Forms;
namespace DoctorScheduleManagementSystem
{
    public class PaymentForm : Form
    {
        int appointmentId; decimal baseAmount=800, discountAmount=0, finalAmount=800; ComboBox cmbCaseType,cmbMethod; TextBox txtCoupon; Label lblBase,lblDiscount,lblFinal;
        public PaymentForm(int appointmentId){this.appointmentId=appointmentId;Text="Payment";Size=new Size(540,480);StartPosition=FormStartPosition.CenterScreen;Label title=new Label{Text="Appointment Payment",Font=new Font("Arial",18,FontStyle.Bold),AutoSize=true,Location=new Point(145,25)};Label info=new Label{Text="Appointment ID: "+appointmentId,Location=new Point(70,75),AutoSize=true};Label lCase=new Label{Text="Case Type",Location=new Point(70,120),AutoSize=true};cmbCaseType=new ComboBox{Location=new Point(200,115),Width=230,DropDownStyle=ComboBoxStyle.DropDownList};cmbCaseType.Items.AddRange(new string[]{"General","Student","Senior Citizen","Diabetes","Emergency"});Label lCoupon=new Label{Text="Coupon Code",Location=new Point(70,165),AutoSize=true};txtCoupon=new TextBox{Location=new Point(200,160),Width=230};Button btnApply=new Button{Text="Apply Discount",Location=new Point(200,200),Width=130};btnApply.Click+=BtnApply_Click;lblBase=new Label{Text="Base Fee: 800",Location=new Point(70,250),AutoSize=true};lblDiscount=new Label{Text="Discount: 0",Location=new Point(70,285),AutoSize=true};lblFinal=new Label{Text="Final Amount: 800",Location=new Point(70,320),AutoSize=true,Font=new Font("Arial",11,FontStyle.Bold)};Label lMethod=new Label{Text="Payment Method",Location=new Point(70,360),AutoSize=true};cmbMethod=new ComboBox{Location=new Point(200,355),Width=230,DropDownStyle=ComboBoxStyle.DropDownList};cmbMethod.Items.AddRange(new string[]{"Cash","Bkash","Nagad","Card"});Button btnPay=new Button{Text="Confirm Payment",Location=new Point(200,405),Width=150};btnPay.Click+=BtnPay_Click;Controls.AddRange(new Control[]{title,info,lCase,cmbCaseType,lCoupon,txtCoupon,btnApply,lblBase,lblDiscount,lblFinal,lMethod,cmbMethod,btnPay});cmbCaseType.SelectedIndex=0;cmbMethod.SelectedIndex=0;}
        void BtnApply_Click(object sender,EventArgs e){discountAmount=0;finalAmount=baseAmount;string coupon=txtCoupon.Text.Trim();string caseType=cmbCaseType.Text;if(coupon==""&&caseType=="General"){UpdateLabels();MessageBox.Show("No coupon or special case selected.");return;}DataTable dt=Db.GetData(@"SELECT TOP 1 * FROM Coupons WHERE CouponCode=@code OR CaseType=@caseType",new SqlParameter("@code",coupon),new SqlParameter("@caseType",caseType));if(dt.Rows.Count>0){int percent=Convert.ToInt32(dt.Rows[0]["DiscountPercent"]);discountAmount=baseAmount*percent/100;finalAmount=baseAmount-discountAmount;UpdateLabels();MessageBox.Show("Discount applied: "+percent+"%");}else{UpdateLabels();MessageBox.Show("No valid coupon/special package found.");}}
        void UpdateLabels(){lblBase.Text="Base Fee: "+baseAmount.ToString("0.00");lblDiscount.Text="Discount: "+discountAmount.ToString("0.00");lblFinal.Text="Final Amount: "+finalAmount.ToString("0.00");}
        void BtnPay_Click(object sender,EventArgs e){bool ok=Db.Execute(@"INSERT INTO Payments(AppointmentId,Amount,CouponCode,CaseType,DiscountAmount,FinalAmount,PaymentMethod,PaymentStatus) VALUES(@aid,@amount,@coupon,@caseType,@discount,@final,@method,'Paid')",new SqlParameter("@aid",appointmentId),new SqlParameter("@amount",baseAmount),new SqlParameter("@coupon",txtCoupon.Text.Trim()),new SqlParameter("@caseType",cmbCaseType.Text),new SqlParameter("@discount",discountAmount),new SqlParameter("@final",finalAmount),new SqlParameter("@method",cmbMethod.Text));if(ok){Db.Execute("UPDATE Appointments SET Status='Booked' WHERE AppointmentId=@id",new SqlParameter("@id",appointmentId));MessageBox.Show("Payment successful. Appointment confirmed.");Close();}}
    }
}
