using System;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Windows.Forms;
namespace DoctorScheduleManagementSystem
{
    public class ScheduleManagementForm : Form
    {
        ComboBox cmbDoctor,cmbDay,cmbStatus; TextBox txtId,txtStart,txtEnd; DataGridView grid;
        public ScheduleManagementForm(){Text="Schedule Management";Size=new Size(870,570);StartPosition=FormStartPosition.CenterScreen;Controls.Add(new Label{Text="Schedule Management",Font=new Font("Arial",18,FontStyle.Bold),AutoSize=true,Location=new Point(290,20)});txtId=AddTextBox("Schedule ID",75,true);Label lDoc=new Label{Text="Doctor",Location=new Point(60,120),AutoSize=true};cmbDoctor=new ComboBox{Location=new Point(185,115),Width=220,DropDownStyle=ComboBoxStyle.DropDownList};Label lDay=new Label{Text="Day",Location=new Point(60,160),AutoSize=true};cmbDay=new ComboBox{Location=new Point(185,155),Width=220,DropDownStyle=ComboBoxStyle.DropDownList};cmbDay.Items.AddRange(new string[]{"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"});txtStart=AddTextBox("Start Time",200,false);txtEnd=AddTextBox("End Time",240,false);Label lStatus=new Label{Text="Status",Location=new Point(60,285),AutoSize=true};cmbStatus=new ComboBox{Location=new Point(185,280),Width=220,DropDownStyle=ComboBoxStyle.DropDownList};cmbStatus.Items.AddRange(new string[]{"Available","Booked"});Button btnAdd=new Button{Text="Add",Location=new Point(475,95),Width=95};Button btnUpdate=new Button{Text="Update",Location=new Point(475,140),Width=95};Button btnDelete=new Button{Text="Delete",Location=new Point(475,185),Width=95};Button btnClear=new Button{Text="Clear",Location=new Point(475,230),Width=95};btnAdd.Click+=BtnAdd_Click;btnUpdate.Click+=BtnUpdate_Click;btnDelete.Click+=BtnDelete_Click;btnClear.Click+=(s,e)=>ClearFields();grid=new DataGridView{Location=new Point(40,340),Size=new Size(780,170),ReadOnly=true,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill};grid.CellClick+=Grid_CellClick;Controls.AddRange(new Control[]{lDoc,cmbDoctor,lDay,cmbDay,lStatus,cmbStatus,btnAdd,btnUpdate,btnDelete,btnClear,grid});LoadDoctors();LoadSchedules();}
        TextBox AddTextBox(string label,int y,bool disabled){Label l=new Label{Text=label,Location=new Point(60,y+5),AutoSize=true};TextBox t=new TextBox{Location=new Point(185,y),Width=220,Enabled=!disabled};Controls.Add(l);Controls.Add(t);return t;}
        void LoadDoctors(){DataTable dt=Db.GetData("SELECT DoctorId, DoctorName FROM Doctors");cmbDoctor.DataSource=dt;cmbDoctor.DisplayMember="DoctorName";cmbDoctor.ValueMember="DoctorId";}
        void LoadSchedules(){grid.DataSource=Db.GetData(@"SELECT s.ScheduleId,d.DoctorName,s.DoctorId,s.DayName,s.StartTime,s.EndTime,s.Status FROM DoctorSchedule s INNER JOIN Doctors d ON s.DoctorId=d.DoctorId");}
        void Grid_CellClick(object sender,DataGridViewCellEventArgs e){if(e.RowIndex<0)return;txtId.Text=grid.Rows[e.RowIndex].Cells["ScheduleId"].Value.ToString();cmbDoctor.SelectedValue=grid.Rows[e.RowIndex].Cells["DoctorId"].Value;cmbDay.Text=grid.Rows[e.RowIndex].Cells["DayName"].Value.ToString();txtStart.Text=grid.Rows[e.RowIndex].Cells["StartTime"].Value.ToString();txtEnd.Text=grid.Rows[e.RowIndex].Cells["EndTime"].Value.ToString();cmbStatus.Text=grid.Rows[e.RowIndex].Cells["Status"].Value.ToString();}
        void BtnAdd_Click(object sender,EventArgs e){if(cmbDoctor.SelectedValue==null||cmbDay.Text==""||txtStart.Text==""||txtEnd.Text==""){MessageBox.Show("Fill all schedule information.");return;} bool ok=Db.Execute(@"INSERT INTO DoctorSchedule(DoctorId,DayName,StartTime,EndTime,Status) VALUES(@d,@day,@st,@et,@status)",new SqlParameter("@d",cmbDoctor.SelectedValue),new SqlParameter("@day",cmbDay.Text),new SqlParameter("@st",txtStart.Text),new SqlParameter("@et",txtEnd.Text),new SqlParameter("@status",cmbStatus.Text==""?"Available":cmbStatus.Text));if(ok){LoadSchedules();ClearFields();}}
        void BtnUpdate_Click(object sender,EventArgs e){if(txtId.Text==""){MessageBox.Show("Select a schedule first.");return;} bool ok=Db.Execute(@"UPDATE DoctorSchedule SET DoctorId=@d,DayName=@day,StartTime=@st,EndTime=@et,Status=@status WHERE ScheduleId=@id",new SqlParameter("@d",cmbDoctor.SelectedValue),new SqlParameter("@day",cmbDay.Text),new SqlParameter("@st",txtStart.Text),new SqlParameter("@et",txtEnd.Text),new SqlParameter("@status",cmbStatus.Text),new SqlParameter("@id",txtId.Text));if(ok){LoadSchedules();ClearFields();}}
        void BtnDelete_Click(object sender,EventArgs e){if(txtId.Text==""){MessageBox.Show("Select a schedule first.");return;} bool ok=Db.Execute("DELETE FROM DoctorSchedule WHERE ScheduleId=@id",new SqlParameter("@id",txtId.Text));if(ok){LoadSchedules();ClearFields();}}
        void ClearFields(){txtId.Clear();txtStart.Clear();txtEnd.Clear();cmbDay.SelectedIndex=-1;cmbStatus.SelectedIndex=-1;}
    }
}
